### ISSUE TITLE
Please upgrade to JSDOM 13.2.0

### ISSUE THREAD

**Issue by JSchermers** [theneva/jest-environment-jsdom-thirteen#2]
In [jest-envrironment-jsdom@24.0.0](https://www.npmjs.com/package/jest-environment-jsdom) the JSDOM 11.5.1 is referenced. But that version does not support [mutationObserver](https://developer.mozilla.org/nl/docs/Web/API/MutationObserver). The latest JSDOM 13.2.0 does support mutationObserver but Jest cannot support it cause node backwards [compat issues](https://github.com/facebook/jest/issues/7926) 

In the past we had to rely on:
* [solution 1](https://stackoverflow.com/questions/48809753/testing-mutationobserver-with-jest)
* [solution 2](https://github.com/thymikee/jest-preset-angular/issues/63)

Reference to [mutation observer in JSDOM](https://github.com/jsdom/jsdom/issues/639)

Is it possible to upgrade jest-environment-jsdom-thirteen

many tnx in advance

**Comment by SimenB** [comment]
https://github.com/theneva/jest-environment-jsdom-thirteen/blob/2db469729ce6c240a553c9767d00fd7e19efe5e7/package.json#L10

It's in semver range? Did you try to install it?

**Comment by JSchermers** [comment]
Hi Simen, 

thanx for your help!

yes i did!

And when i add it to
"testEnvironment": "jest-environment-jsdom-thirteen" in package.json it does not work.  I still get MutationObserver is not defined when running jest. When i just update the jsdom package inside jest-environment-jsdom manually. It does work. So i figured jest-environment-jsdom-thirteen, the jsdom did not work.

I see the correct version being referenced in package.lock.json
"https://registry.npmjs.org/jsdom/-/jsdom-13.2.0.tgz",

any idea?

Btw i'm new to jest. We are trying to switch from karma/jasmine to jest.

tnx

**Comment by jopdeklein** [comment]
I did a fresh install and it seems to work for me @JSchermers.

**Comment by JSchermers** [comment]
Yes, thank you @jopdeklein . I think this was a local issue with npm. Deleting node_modules and installing again did the trick. 

Jest now works with the new JSDOM with "testEnvironment": "jest-environment-jsdom-thirteen",
