### ISSUE TITLE
Upgrade Jest dependencies

### ISSUE THREAD

**Issue by SimenB** [theneva/jest-environment-jsdom-thirteen#4]
They're old, hairy and outdated

https://github.com/theneva/jest-environment-jsdom-thirteen/blob/d83782a0bfeb1a169584aef95ba70860fa4b955e/package.json#L8-L9

**Comment by theneva** [comment]
Good catch! I just released v1.0.0 which uses Jest ^24.1.0 for testing, and depends on jest-mock and jest-util ^24.0.0.
